### ISSUE TITLE
JMP 

### ISSUE THREAD

**Issue by svalazar** [Kaptch/asmClockCounter#2]
Ошибка при вычислении числа тактов для JMP. См. стр.2-58 http://edu.mmcs.sfedu.ru/pluginfile.php/33079/mod_resource/content/1/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D1%8F%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B9%20%D0%B0%D1%81%D1%81%D0%B5%D0%BC%D0%B1%D0%BB%D0%B5%D1%80%D0%B0.pdf

**Comment by svalazar** [comment]
День добрый, Сергей!
Ошибка с подсчетом JMP исправлена.
А что Вы скажете по поводу вот этого кусочка?
-- LOOP
--I1 LOOP (OPM _) -> 17 :+ 0
-- LOOPZ
--I1 LOOPZ (OPM _) -> 18 :+ 0
-- LOOPNZ
--I1 LOOPNZ (OPM _) -> 19 :+ 0
-- REP
Поскольку сейчас уже близится сессия, то можно эти правки оставить до
консультации перед экзаменом 8-)

С уважением,
Светлана Александровна Лазарева
_____________________
доц. Института математики, механики и компьютерных наук имени И. И. Воровича
Южного федерального университета
sv@sfedu.ru
+7 988 5601150




сб, 15 дек. 2018 г. в 13:09, Sergey <notifications@github.com>:

**Comment by Kaptch** [comment]
Добрый вечер, Светлана Александровна.

Добавил все оставшиеся инструкции контроля потока вычисления. Я просто
думал, что их лучше вообще не считать, раз уж программа не рассчитана на
трассировку. Добавил также push для чисел, значение количества тактов взял
не из таблицы, а посчитал вручную. Странно, что в таблице этого не было.

С уважением,
Сергей Степаненко

**Comment by svalazar** [comment]
ОК, Сергей. Основные тесты пройдёны.   Я ещё "погоняю" окончательный
вариант на разных дополнительных тестах. Вдруг, ещё что-нибудь обнаружу. 8-)
Я бы хотела рассказать о Ваших с Никитой работах в сообществе
преподавателей курса "Архитектура ..." по Таненбауму. Что скажете?
Планируете ли Вы держать на Гитхабе этот код? Планируете ли Вы разрешить
скачивать  исполнимый файл всем заинтересованным? Или следует
подредактировать лицензионное соглашение?

С уважением,
Светлана Александровна Лазарева
_____________________
доц. Института математики, механики и компьютерных наук имени И. И. Воровича
Южного федерального университета
sv@sfedu.ru
+7 988 5601150




вс, 16 дек. 2018 г. в 21:36, Sergey <notifications@github.com>:

**Comment by Kaptch** [comment]
Здравствуйте, Светлана Александровна.

Да, конечно, я не против. Я тогда открою репозиторий и напишу небольшую
инструкцию, если в будущем кто-то захочет продолжить работать с версией на
Хаскеле.

С уважением,
Сергей Степаненко

**Comment by svalazar** [comment]
Хорошо, а когда сделаете всё намеченное, я напишу текст, согласую его с
Вами и с Никитой, затем  отправлю его коллегам. Заодно посмотрю, вдруг это
интересно не только им. 8-)

С уважением,
Светлана Александровна Лазарева
_____________________
доц. Института математики, механики и компьютерных наук имени И. И. Воровича
Южного федерального университета
sv@sfedu.ru
+7 988 5601150




чт, 20 дек. 2018 г. в 08:51, Sergey <notifications@github.com>:

**Comment by Kaptch** [comment]
Переписал readme и вынес исполняемый файл в раздел релизов. Думаю, теперь
выглядит приемлимо.

С уважением,
Сергей Степаненко

чт, 20 дек. 2018 г. в 11:18, Svetlana Lazareva <notifications@github.com>:
